---
version: '2'

services:
  prometheus:
    image: prom/prometheus:v2.3.0
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus-rules.yml:/etc/prometheus/prometheus-rules.yml
      - ./data/prometheus:/prometheus
    command:
      '--config.file=/etc/prometheus/prometheus.yml --web.enable-lifecycle'
    ports:
      - 9090:9090
    user: 'root'

  grafana:
    image: grafana/grafana:5.4.2
    volumes:
      - ./data/grafana:/var/lib/grafana
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    user: 'root'
