global:
  # How frequently to scrape targets
  scrape_interval: 10s

  # How frequently to evaluate rules.
  evaluation_interval: 10s

  external_labels:
    monitor: 'local-services'

scrape_configs:
  - job_name: 'local-service'
    tls_config:
      insecure_skip_verify: true
    scheme: http
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:5050']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['host.docker.internal:9090']

rule_files:
- "prometheus-rules.yml"
